In [1]:
import numpy as np

In [2]:
def constructCDG(PDG_list):
    n = len(PDG_list)
    CDG = np.zeros((n,n))
    for PDG in PDG_list:
        CDG = np.logical_or(CDG,PDG)
    return CDG

In [3]:
##we want individual graphs to be of this form

##N X N graph where if (i,j) is 1 then i is yeilding to j



In [4]:
##test case 1
PDG_0 = np.array([[1,0,0],
        [0,0,0],
        [0,0,0]])

PDG_1 = np.array([[1,0,0],
        [0,0,1],
        [0,0,0]])

PDG_2 = np.array([[0,0,0],
        [0,0,1],
        [0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2]
constructCDG(PDG_list)

array([[ True, False, False],
       [False, False,  True],
       [False, False, False]])

In [5]:
##test case 2
PDG_0 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_1 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_2 = np.array([[0,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_3 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2, PDG_3]
constructCDG(PDG_list)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [6]:
##test case 3
PDG_0 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_1 = np.array([[1,0,0,0],
        [0,0,1,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_2 = np.array([[0,0,0,0],
        [0,0,1,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_3 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2, PDG_3]
CDG = constructCDG(PDG_list)

In [28]:
def DFS(CDG, visited, parent,start,n):
    visited[start] = -1
    cycle = []
    flag =0
    for i in range(n):
        if(CDG[start][i]==True):
            if(visited[i]==0):
                parent[i] = start
                cycle = DFS(CDG, visited, parent, i,n)
                if(cycle!=[]):
                    return cycle
            elif(visited[i]==-1):#cycle detected
                # print("entered here")
                # print(start)
                # print(parent)
                # print(i)
                j = start
                while(parent[j]!=i):
                    cycle.append(j)
                    j = parent[j]
                cycle.append(j)
                cycle.append(i)
                return cycle     
                # cycle = [1,4,6]
                # return cycle     

    # print("tf")
    visited[start] = 1
    return cycle

In [25]:
##finding cycles
##function is expected to find exactly one cycle and return the nodes invovled in the cycle
def findCycles(CDG):
    n = CDG.shape[0]
    visited = np.zeros(n)
    parent = np.arange(n)
    for start in range(n):
        if(visited[start]==0):
            cycle = DFS(CDG,visited,parent,start,n)
            print("Cyle: ", cycle)
            if(cycle != []):
                return cycle
    return []

In [19]:
##test 1
PDG_0 = np.array([[0,1,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_1 = np.array([[0,1,0,0],
        [0,0,1,0],
        [0,0,0,0],
        [1,0,0,0]])

PDG_2 = np.array([[0,0,0,0],
        [0,0,1,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_3 = np.array([[0,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [1,0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2, PDG_3]
CDG = constructCDG(PDG_list)
print(CDG)
print(findCycles(CDG))

[[False  True False False]
 [False False  True False]
 [False False False  True]
 [ True False False False]]
Cyle:  [3, 2, 1, 0]
[3, 2, 1, 0]


In [21]:
CDG = np.array([[False,True,False,False,False,False,False],
                [False,False,True,False,True,False,False],
                [True,False,False,False,False,True,False],
                [False,False,False,False,False,False,False],
                [False,False,False,False,False,False,False],
                [False,False,False,False,False,True,False],
                [False,True,False,False,False,False,False]])
print(CDG)
print(findCycles(CDG))

[[False  True False False False False False]
 [False False  True False  True False False]
 [ True False False False False  True False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False  True False]
 [False  True False False False False False]]
Cyle:  [2, 1, 0]
[2, 1, 0]


In [30]:
CDG = np.array([[False,True,False,True,False,False,False],
                [False,False,True,False,True,False,False],
                [False,False,False,False,False,True,False],
                [False,False,False,False,False,False,False],
                [False,False,False,False,False,False,False],
                [False,False,False,False,False,False,True],
                [False,True,False,False,False,False,False]])
print(CDG)
print(findCycles(CDG))

[[False  True False  True False False False]
 [False False  True False  True False False]
 [False False False False False  True False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False  True]
 [False  True False False False False False]]
entered here
6
[0 0 1 3 4 2 5]
1
Cyle:  [6, 5, 2, 1]
[6, 5, 2, 1]
