In [2]:
import numpy as np

In [3]:
def constructCDG(PDG_list):
    n = len(PDG_list)
    CDG = np.zeros((n,n))
    for PDG in PDG_list:
        CDG = np.logical_or(CDG,PDG)
    return CDG

In [ ]:
##we want individual graphs to be of this form

##N X N graph where if (i,j) is 1 then i is yeilding to j



In [7]:
##test case 1
PDG_0 = np.array([[1,0,0],
        [0,0,0],
        [0,0,0]])

PDG_1 = np.array([[1,0,0],
        [0,0,1],
        [0,0,0]])

PDG_2 = np.array([[0,0,0],
        [0,0,1],
        [0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2]
constructCDG(PDG_list)

array([[ True, False, False],
       [False, False,  True],
       [False, False, False]])

In [8]:
##test case 2
PDG_0 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_1 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_2 = np.array([[0,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_3 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2, PDG_3]
constructCDG(PDG_list)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [9]:
##test case 3
PDG_0 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_1 = np.array([[1,0,0,0],
        [0,0,1,0],
        [0,0,0,0],
        [0,0,0,0]])

PDG_2 = np.array([[0,0,0,0],
        [0,0,1,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_3 = np.array([[1,0,0,0],
        [0,0,0,0],
        [0,0,0,1],
        [0,0,0,0]])

PDG_list = [PDG_0,PDG_1,PDG_2, PDG_3]
constructCDG(PDG_list)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])